# Generated by Django 5.1.4 on 2024-12-27 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="products.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_products", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
